---
- hosts: db
  become: yes
  tasks:

  - name: create file
    copy:
      dest: /mnt/mysql_backups/database_list.txt
      content: "dev,test,qa,prod"

  - name: check if file exists
    stat:
      path: /mnt/mysql_backups/database_list.txt
    register: stat_out

  - name: compress file
    archive:
      path: /mnt/mysql_backups/database_list.txt
      dest: /mnt/mysql_backups/archive.gz
      format: gz
    when: stat_out.stat.exists


