---
- hosts: db
  become: 1
  tasks:

  - name: create directory
    file:
      state: directory
      path: /etc/ansible/facts.d
      mode: 0755

  - name: create a fact
    copy:
      dest: /etc/ansible/facts.d/custom.fact
      content: |
        [sample_exam]
        server_role=mysql

  - name: get facts
    setup:

  - debug:
      var: ansible_local.custom.sample_exam.server_role
